### ISSUE TITLE
Archiv/Nowcast_R_2022-07-23.csv fehlt

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung#12]
Hi,

der Upload des Nowcast gestern schlug wohl fehl und "Nowcast_R_2022-07-23.csv" fehlt nun im Archiv.

**Comment by RKIOpenData** [comment]
Hi @icestorm972 ,

ich hab die fehlende Datei nochmal manuell hochgeladen.

Mit besten Grüßen
Knut Perseke
für das Team RKI | Open Data
