### ISSUE TITLE
Update 2022-10-04 ausgefallen, Archiv/Nowcast_R_2022-10-04.csv fehlt

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung#13]
Hi,

das gestrige (2022-10-04) Update ging wohl schief und Archiv/Nowcast_R_2022-10-04.csv fehlt nun.

Viele Grüße
David

**Comment by HannesWuensche** [comment]
Hallo @icestorm972 ,

Besten Dank für den Hinweis. Das ist tatsächlich untergegangen. Die Daten sind jetzt im Archiv. 

Beste Grüße
@HannesWuensche 
für das Team RKI | Open Data
