### ISSUE TITLE
Update ist noch nicht da.

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung#16]

**Comment by icestorm972** [comment]
Updates 2022-11-27 & 2022-11-28 scheinen ausgefallen zu sein, und damit fehlen auch die Nowcast_R_2022-11-27.csv & Nowcast_R_2022-11-28.csv im Archiv.

**Comment by HannesWuensche** [comment]
Liebe Alle,

wir sind dran. Die Daten sollten in 2-3h bereitstehen. 

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data
