### ISSUE TITLE
aktuelle Datei "22.5.23" ist die vom 20.5.

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung#20]
Dateien vom 21.5. und 22.5. fehlen noch.

**Comment by HannesWuensche** [comment]
Hallo @Rutger265,

vielen Dank für den Hinweis, ich habe das Archiv soeben aktualisiert. 

Beste Grüße
@HannesWuensche 
für das Team RKI | Open Data
