### ISSUE TITLE
Fehlender Nowcast_R_2021-11-12.csv im Archiv

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung#3]
Der Nowcast gestern ist ausgefallen. 
Es wäre super, falls es möglich wäre, den noch nachträglich im Archiv zu haben.

**Comment by rebzdu** [comment]
Schließe mich der Bitte an

**Comment by HannesWuensche** [comment]
Hallo @icestorm972 ,

vielen Dank für den Hinweis.
Wir haben die fehlende Datei dem Archiv hinzugefügt.

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
