### ISSUE TITLE
unnötige Kopie der csv Daten ins Archiv

### ISSUE THREAD

**Issue by volviq** [robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung#4]
Auf einer Wbsite würde es Sinn machen, alte Versionen in einem Archiv Ordner zu kopieren, bevor eine neue Version erstellt wir.
In git ist die Hauptdate jedoch schon das Archiv, bzw git erledigt das.
Wie man in: https://github.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/commits/main/Nowcast_R_aktuell.csv
sieht, gibt es dort eine Historie aller Dateien, seit das Repository initialisiert wurde.
Das Repository würde dadurch Platz einsparen, dennoch wären die Historischen Daten zugreifbar.
Es ist für Betrachtungen in diesem Fall auch nur sehr selten nötig, alte Daten zu betrachten, da das csv sowieso eine Zeitreihe von Anbeginn der pandemie ist.

mein Vorschlag: keine neuen Dateien mehr ins Archiv verschieben, sondern auf die git history verweisen, falls man auf alte versionen zugreifen will. Ausschliesslich Dateien, die erstellt wurden, bevor das git repo erstellt wurden, benötigt man im Archiv Ordner.

**Comment by HannesWuensche** [comment]
Hallo @volviq,

vollkommen richtig. Im Datensatz der Infektionszahlen gibt es bereits ein ähnliches Issue: https://github.com/robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland/issues/10

Wir stellen das Archiv aus Gründen der Bequemlichkeit für diejenigen bereit, die einen einfachen Zugriff auf alle Dateien der Historie benötigen. Dass die Datensätze dadurch sehr groß werden ist uns bewusst, wir arbeiten derzeit an einer Lösung die versucht alle Anforderungen unter einen Hut zu bekommen und bitte noch um etwas Geduld. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by volviq** [comment]
dann wäre es vielleicht sinnvoll ein Archiv Repo zu machen in alle diese history files zusammen abgespeichert werden. und die Themen-Repos können im git style bleiben, bzw dahin konvertiert werden.

**Comment by Byggvir** [comment]
Die Dateien im Archiv haben ihre Berechtigung, weil sie den Stand zum jeweiligen Tag angeben. Es ändert sich nicht nur der letzte Tag.

Eine Alternative wäre eine Erweiterung um ein Datenfeld mit dem Berechnungsdatum. Dann wird allerdings diese Datei sehr groß.

M.E. ist die Lösung so akzeptabel. Wer alle Daten braucht, kann sie aus dem Archiv leicht zusammenbauen.

Leider fehlen historische Daten vom dem 16. März.

**Comment by Ein-Tim** [comment]
Das Archiv scheint ziemlich Hilfreich zu sein, siehe z.B.: https://github.com/corona-warn-app/cwa-documentation/issues/872#issuecomment-1073284877 von @MikeMcC399.
