### ISSUE TITLE
Datei zum 2021-06-30 im Archiv abweichend

### ISSUE THREAD

**Issue by jenuk** [robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung#5]
DIe Datei [Archiv/Nowcast_R_2021-06-30.csv](https://github.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/blob/main/Archiv/Nowcast_R_2021-06-30.csv) ist anders formatiert als der Rest. Das Datum ist in der Form "DD:MM:YYYY" statt "YYYY-MM-DD" angegeben, am Ende steht eine Erläuterung der Daten (die Anführungszeichen enthält) und die Werte sind durch Semikolons statt Kommas voneinader getrennt

**Comment by HannesWuensche** [comment]
Hallo @jenuk,

Dank @Byggvir sollte das Problem gelöst sein. Nochmals Danke. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
