### ISSUE TITLE
Heutiger (2022-01-29) Nowcast fehlt

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung#8]
Hi,

bisher gab es kein Update.

Viele Grüße

**Comment by analphabit** [comment]
Hallo RKI,

wird die Datei mit dem heutigen Nowcast (29.01.2022) noch eingestellt? Wäre prima.

Danke und Grüße

**Comment by HannesWuensche** [comment]
Hallo @icestorm972,
Hallo @analphabit,

das Nowcasting ist nicht eingestellt. Wir werden den Daten im Verlauf des Tages bereitstellen, haben aber leider derzeit etwas Verzögerung und bitten um Verständnis. 

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data
