### ISSUE TITLE
Fehlender Upload/CSV am 2022-04-21 und damit auch Archiv/Nowcast_R_2022-04-21.csv

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung#9]
Der Upload gestern (2022-04-21) ging wohl schief und fehlt jetzt im Archiv.

Viele Grüße
David

**Comment by HannesWuensche** [comment]
Hallo @icestorm972,

danke für die Rückmeldung.
Leider ist das Fehlen der Daten gestern leider untergegangen, jetzt nachgetragen.

Mit besten Grüßen
@HannesWuensche für das Team RKI | OpenData
